name: Deploy Go to Railway

on:
  push:
    paths:
      - 'school-library-server/**'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: ${{ secrets.RAILWAY_SERVICE_NAME }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    steps:
      - name: Checkout code
        working-directory: ./school-library-server
        uses: actions/checkout@v3

      - name: Debug folder
        working-directory: ./school-library-server
        run: ls -lah

      - run: railway up --service=${{ env.SVC_ID }} --detach

